### ISSUE TITLE
Pitest failFast skipped testng aftermethod , even use always = run 

### ISSUE THREAD

**Issue by wlopper** [pitest/pitest-testng-plugin#2]
![image](https://user-images.githubusercontent.com/54232090/215313200-eb038592-a2cc-4d18-ab70-eacd0ffed527.png)

**Comment by wlopper** [comment]
I did the database rollback operation in the aftermethod step of testng. Now if the test case fails, the aftermethod will be skipped and the transaction cannot be rolled back

**Comment by wlopper** [comment]
Even if alwaysrun=true is configured, it will still be skipped. Is there any way to exit the test case after the test case fails

**Comment by hcoles** [comment]
Hi @wlopper,

The short answer is, I don't know. Pitest delegates most of the running of the tests to TestNG. If it is not honouring the alwaysrun flag, it would need someone to create a test case that reproduces this issue and debug. Unfortunately I am not able to look at this at the moment due to other commitments. If you are able to debug the issue I would be happy to accept a pull request.

**Comment by wlopper** [comment]
Hello, @hcoles . After my investigation, I found that the reason is that FailFast implements the IInvokedMethodListener interface. In the beforeInvocation method, it only judges whether there are failed use cases. If there are, it throws a SkipException exception, which interrupts the execution of testng. We can add another condition, such as: method is not modified by @ AfterXXX annotation. For example:
![image](https://user-images.githubusercontent.com/54232090/215434851-b3bb2a9e-21f0-4359-ba83-624b739090f3.png)

This solution is not the best. We can add configuration items to set which methods are not skipped, such as whether the annotation is annotated by @ AfterXXX, whether it is annotated by @ BeforeXXX, or whether the annotation is marked with alwaysrun=true, I think some resource fallback operations (such as the transaction management of spring-testng) are performed in the @ AfterMethod annotation method. So I just want to add this judgment at present. In short, this is a problem that can be solved, and I think it is better not to skip the @ AfterXXX method

**Comment by wlopper** [comment]
`    @Override
    public void beforeInvocation(IInvokedMethod method, ITestResult testResult) {
        if (this.listener.hasHadFailure() && notAfterConfiguration(method)) {
            throw new SkipException("Skipping");
        }
    }

    private boolean notAfterConfiguration(IInvokedMethod method) {
        ITestNGMethod testMethod = method.getTestMethod();
        boolean flag = testMethod.isAfterClassConfiguration()
            || testMethod.isAfterMethodConfiguration()
            || testMethod.isAfterGroupsConfiguration()
            || testMethod.isAfterSuiteConfiguration()
            || testMethod.isAfterTestConfiguration();
        return !flag;
    }`

**Comment by wlopper** [comment]
` 
   @Override
    public void beforeInvocation(IInvokedMethod method, ITestResult testResult) {
        if (this.listener.hasHadFailure() && notAfterConfiguration(method)) {
            throw new SkipException("Skipping");
        }
    }

    private boolean notAfterConfiguration(IInvokedMethod method) {
        ITestNGMethod testMethod = method.getTestMethod();
        boolean flag = testMethod.isAfterClassConfiguration()
            || testMethod.isAfterMethodConfiguration()
            || testMethod.isAfterGroupsConfiguration()
            || testMethod.isAfterSuiteConfiguration()
            || testMethod.isAfterTestConfiguration();
        return !flag;
    }
`

**Comment by wlopper** [comment]
@Override
    public void beforeInvocation(IInvokedMethod method, ITestResult testResult) {
        if (this.listener.hasHadFailure() && notAfterConfiguration(method)) {
            throw new SkipException("Skipping");
        }
    }

    private boolean notAfterConfiguration(IInvokedMethod method) {
        ITestNGMethod testMethod = method.getTestMethod();
        boolean flag = testMethod.isAfterClassConfiguration()
            || testMethod.isAfterMethodConfiguration()
            || testMethod.isAfterGroupsConfiguration()
            || testMethod.isAfterSuiteConfiguration()
            || testMethod.isAfterTestConfiguration();
        return !flag;
    }
